---
node_exporter_version: "1.4.0"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz" 

node_exporter_dest_location: "/data/node_exporter"

node_exporter_file_location: "/usr/local/bin/node_exporter"








