---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 8080
    name: nginx
    protocol: TCP
    targetPort: 80
  type: ClusterIP













