---
---
 - name: "ensure dest location exists"
   ansible.builtin.file:
     path: "{{ node_exporter_dest_location }}"
     state: "directory"
     mode: "0744"
 - name: "download node exporter"
   ansible.builtin.unarchive:
     src: "{{ node_exporter_url }}"
     dest: "{{ node_exporter_dest_location }}"
     remote_src: true
     list_files: true 
   register: "unarchive_output"
 - name: "print output"
   ansible.builtin.debug:
     msg: "{{ unarchive_output.files[0] }}"
     # - name: "move binary from /data to /usr/local/bin"
     #   ansible.builtin.copy:
     #     src: "{{ node_exporter_dest_location }}/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"






     #Лекция №17, создание таска, который рекурсивно скачивает файлы по элменетам из списка
     #
     #
     #
     #
     #
     #
     #
     #
