---
 - name: "ensure systemd unit"
   ansible.builtin.template:
     src: "node_exporter.service.j2"
     dest: "/etc/systemd/system/node_exporter.service"
     mode: "0644"
     owner: "root"
     group: "root"
   notify: "restart node_exporter"
 - name: "ensure systemd service is started"
   ansible.builtin.systemd:
     name: "node_exporter"
     state: "started"











