---
prometheus_version: "2.39.1"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz" 

prometheus_dest_location: "/data/prometheus"

prometheus_file_location: "/usr/local/prometheus"









