---
- hosts: "local"
  tasks: 
    - name: "Install docker-ce package"
      ansible.builtin.yum:
        name: "docker-ce"
        state: latest
        update_cache: yes

    - name: "Start docker-ce package"
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started






